### ISSUE TITLE
rlibm_expf

### ISSUE THREAD

**Issue by prank746** [rutgers-apl/The-RLIBM-Project#4]
hello,
the function rlibm_expf is relying on ldexp, but i don't have ldexp currently. Is there an alternative way? thank you.

**Comment by santoshn** [comment]
An alternative way is to implement ldexp by directly adjusting the exponent in the bit-pattern.  We will add a version without ldexp soon.

**Comment by santoshn** [comment]
The latest commit has a expf that does not use ldexp
